name: News Flow Automation

on:
  schedule:
    - cron: '0 * * * *'    # 毎時0分にフェッチ＆ログ追記
    - cron: '0 0 * * *'    # 毎日0時（UTC）に日次サマリーを実行
    # - cron: '0 0 * * 1'    # 毎週月曜0時（UTC）に週次サマリーを実行 (必要ならコメントアウトを外す)
    # - cron: '0 0 1 * *'    # 毎月1日0時（UTC）に月次サマリーを実行 (必要ならコメントアウトを外す)
  workflow_dispatch: # 手動実行も可能

permissions:
  contents: write # リポジトリへの書き込み権限（ログファイル、DB、処理済み記事ログ用）

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # コミット権限用
          persist-credentials: true
          fetch-depth: 0 # 全履歴をフェッチ
          ref: ${{ github.ref }} # 現在のブランチを明示的にチェックアウト

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install MeCab and related libraries # 【変更点: MeCabインストールステップを追加】
        run: |
          sudo apt-get update
          sudo apt-get install -y mecab libmecab-dev mecab-ipadic-utf8
          # mecab-ipadic-neologd をインストールする場合（これは時間がかかる可能性あり）
          # sudo apt-get install -y git make curl
          # git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git
          # cd mecab-ipadic-neologd
          # ./bin/install-mecab-ipadic-neologd -n -y
          # cd ..
          # MeCab Python binding のインストール
          pip install mecab-python3

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt # requirements.txtから依存関係をインストール

      - name: Fetch & Log Keywords
        run: |
          cd "${{ github.workspace }}" # リポジトリのルートディレクトリに移動
          source .venv/bin/activate
          PYTHONPATH="${{ github.workspace }}" python news_fetcher.py # PYTHONPATHを設定してモジュールのパスを通す
      
      - name: Debug Hourly Keyword Log
        run: |
          echo "--- Debugging hourly_keyword_counts.jsonl content ---"
          if [ -f data/hourly_keyword_counts.jsonl ]; then
            head -n 5 data/hourly_keyword_counts.jsonl
            echo "..."
            tail -n 5 data/hourly_keyword_counts.jsonl
          else
            echo "data/hourly_keyword_counts.jsonl does not exist."
          fi
          echo "-----------------------------------------------------"

      - name: Commit Hourly Logs and Processed Articles
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add data/hourly_keyword_counts.jsonl data/processed_articles.json
          git commit -m "chore: update hourly keyword counts and processed articles log" || echo "No changes to commit"
          git push origin main

  summarize_and_notify:
    needs: fetch # fetchジョブが完了してから実行
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.schedule == '0 0 * * *') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # 全履歴をフェッチ
          ref: ${{ github.ref }} # 現在のブランチを明示的にチェックアウト

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create venv & Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          # 日本語フォントをインストール
          sudo apt-get update
          sudo apt-get install -y fonts-ipafont-gothic
          sudo fc-cache -fv # 必要に応じてフォントキャッシュを更新 (通常は不要だが念のため)

      - name: Initialize Database (if not exists)
        run: |
          cd "${{ github.workspace }}" # リポジトリのルートディレクトリに移動
          source .venv/bin/activate
          PYTHONPATH="${{ github.workspace }}" python db_manager.py

      - name: Debug DB Content
        run: |
          echo "--- Debugging keyword_trends.db content ---"
          sqlite3 data/keyword_trends.db ".schema"
          sqlite3 data/keyword_trends.db "SELECT * FROM daily_trends LIMIT 20;"
          sqlite3 data/keyword_trends.db "SELECT date, trend_type, source_name, COUNT(keyword) FROM daily_trends GROUP BY date, trend_type, source_name ORDER BY date DESC LIMIT 10;"
          sqlite3 data/keyword_trends.db "SELECT date, trend_type, source_name, keyword, count FROM daily_trends ORDER BY date DESC, trend_type, source_name, count DESC LIMIT 20;"
          echo "-------------------------------------------"

      - name: Run Summarizer and Get Report
        id: run_summarizer
        run: |
          cd "${{ github.workspace }}" # リポジトリのルートディレクトリに移動
          source .venv/bin/activate
          echo "full_summary_output<<EOF" >> $GITHUB_OUTPUT
          PYTHONPATH="${{ github.workspace }}" python summarize.py >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Notify Discord 24H Trends
        if: success() && contains(steps.run_summarizer.outputs.full_summary_output, '---REPORT_SPLIT---24H')
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL_24H }}
        run: |
          full_output="${{ steps.run_summarizer.outputs.full_summary_output }}"
          content_24h=$(echo "$full_output" | sed -n '/---REPORT_SPLIT---24H/,/---REPORT_SPLIT---1MON/p' | sed '1d;$d')
          
          if [ $(echo -n "$content_24h" | wc -c) -gt 1990 ]; then
            echo "Warning: 24H report content exceeds 2000 characters. Trimming..."
            content_24h=$(echo "$content_24h" | cut -c 1-1990)"..."
          fi

          if [ -n "$content_24h" ]; then
            payload=$(jq -Rn --arg c "$content_24h" '{content: $c}')
            curl -H "Content-Type: application/json" \
                 -d "$payload" \
                 "$DISCORD_WEBHOOK_URL"
          else
            echo "24H trends report is empty, skipping Discord notification."
          fi

      - name: Notify Discord 1MON Trends
        if: success() && contains(steps.run_summarizer.outputs.full_summary_output, '---REPORT_SPLIT---1MON')
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL_1MON }}
        run: |
          full_output="${{ steps.run_summarizer.outputs.full_summary_output }}"
          content_1m=$(echo "$full_output" | sed -n '/---REPORT_SPLIT---1MON/,/---REPORT_SPLIT---3MON/p' | sed '1d;$d')

          if [ $(echo -n "$content_1m" | wc -c) -gt 1990 ]; then
            echo "Warning: 1MON report content exceeds 2000 characters. Trimming..."
            content_1m=$(echo "$content_1m" | cut -c 1-1990)"..."
          fi

          if [ -n "$content_1m" ]; then
            payload=$(jq -Rn --arg c "$content_1m" '{content: $c}')
            curl -H "Content-Type: application/json" \
                 -d "$payload" \
                 "$DISCORD_WEBHOOK_URL"
          else
            echo "1MON trends report is empty, skipping Discord notification."
          fi

      - name: Notify Discord 3MON Trends
        if: success() && contains(steps.run_summarizer.outputs.full_summary_output, '---REPORT_SPLIT---3MON')
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL_3MON }}
        run: |
          full_output="${{ steps.run_summarizer.outputs.full_summary_output }}"
          content_3m=$(echo "$full_output" | sed -n '/---REPORT_SPLIT---3MON/,$p' | sed '1d')

          if [ $(echo -n "$content_3m" | wc -c) -gt 1990 ]; then
            echo "Warning: 3MON report content exceeds 2000 characters. Trimming..."
            content_3m=$(echo "$content_3m" | cut -c 1-1990)"..."
          fi

          if [ -n "$content_3m" ]; then
            payload=$(jq -Rn --arg c "$content_3m" '{content: $c}')
            curl -H "Content-Type: application/json" \
                 -d "$payload" \
                 "${{ secrets.DISCORD_WEBHOOK_URL_3MON }}"
          else
            echo "3MON trends report is empty, skipping Discord notification."
          fi
      
      - name: Generate Word Clouds
        run: |
          cd "${{ github.workspace }}"
          source .venv/bin/activate
          mkdir -p data/wordclouds
          PYTHONPATH="${{ github.workspace }}" python generate_wordclouds.py
      
      - name: Commit Word Clouds
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add data/wordclouds/*.png
          git commit -m "chore: add generated word cloud images" || echo "No new word cloud images to commit"
          git push origin main
      
      - name: Get Word Cloud URLs and Notify Discord
        if: success()
        run: |
          REPO_NAME="${{ github.repository }}"
          BRANCH_NAME="${{ github.ref_name }}"
          
          IMAGE_PATHS=$(find data/wordclouds -name "*.png")
          
          DISCORD_MESSAGE=""
          for IMAGE_PATH in $IMAGE_PATHS; do
            IMAGE_BASENAME=$(basename "$IMAGE_PATH")
            IMAGE_URL="https://raw.githubusercontent.com/$REPO_NAME/$BRANCH_NAME/$IMAGE_PATH"
            TITLE_FORMATTED=$(echo "$IMAGE_BASENAME" | sed 's/wordcloud_//' | sed 's/\.png//' | sed 's/_/\ /g' | sed 's/24h/24時間トレンド/g' | sed 's/1m/1ヶ月トレンド/g' | sed 's/3m/3ヶ月トレンド/g' | sed 's/bitcoin.com news/Bitcoin.com News/g' | sed 's/cointelegraph/Cointelegraph/g' | sed 's/cryptonews/CryptoNews/g' | sed 's/decrypt/Decrypt/g' | sed 's/total/全体/g' | sed 's/\([0-9]\{4\}\)\([0-9]\{2\}\)\([0-9]\{2\}\)/\1年\2月\3日/g')
            
            DISCORD_MESSAGE+="## ワードクラウドレポート: $TITLE_FORMATTED\n"
            DISCORD_MESSAGE+="$IMAGE_URL\n\n"
          done
          
          if [ $(echo -n "$DISCORD_MESSAGE" | wc -c) -gt 1990 ]; then
            echo "Warning: Discord image report content exceeds 2000 characters. Trimming..."
            DISCORD_MESSAGE=$(echo "$DISCORD_MESSAGE" | cut -c 1-1990)"..."
          fi

          if [ -n "$DISCORD_MESSAGE" ]; then
            payload=$(jq -Rn --arg c "$DISCORD_MESSAGE" '{content: $c}')
            curl -H "Content-Type: application/json" \
                 -d "$payload" \
                 "${{ secrets.DISCORD_WEBHOOK_URL_WORDCLOUDS }}"
          else
            echo "No word cloud images generated, skipping Discord notification."
          fi
      
      - name: Commit Summary and Database Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add data/keyword_trends.db
          git commit -m "chore: update daily keyword trends DB" || echo "No changes to commit"
          git push origin main
