name: News Flow Automation

on:
  schedule:
    - cron: '0 * * * *'    # 毎時0分にフェッチ＆ログ追記
    - cron: '0 0 * * *'    # 毎日0時（UTC）にサマリー実行 (将来的に週次・月次も追加)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip feedparser

      - name: Fetch & Log Keywords
        run: |
          source .venv/bin/activate
          python news_fetcher.py

      - name: Commit Keyword Logs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add data/hourly_keyword_counts.jsonl data/processed_articles.json
          git commit -m "chore: update hourly keyword counts and processed articles log" || echo "No changes to commit"
          git push origin main

  summarize_and_notify:
    needs: fetch
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.schedule == '0 0 * * *') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create venv & install deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip

      # --- ここにsummarizer.pyとnotification_helper.pyの実行ステップが将来追加されます ---
      - name: Placeholder for Summarize and Notify
        run: |
          echo "Summarization and notification will be implemented in the next steps."
          echo "This job runs daily or on manual trigger."
