name: News Flow Automation
on:
  schedule:
    - cron: '0 * * * *'    # 毎時0分にフェッチ＆ログ追記
    - cron: '0 0 * * *'    # 毎日0時（UTC）に日次サマリーを実行
  workflow_dispatch: # 手動実行も可能
permissions:
  contents: write # リポジトリへの書き込み権限（ログファイル、DB、処理済み記事ログ用）
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # コミット権限用
          persist-credentials: true
          fetch-depth: 0 # 全履歴をフェッチ
          ref: ${{ github.ref }} # 現在のブランチを明示的にチェックアウト

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install MeCab system libraries and alternative dictionary
        run: |
          sudo apt-get update
          echo "--- Purging existing MeCab ipadic/jumandic packages ---"
          sudo apt-get purge -y mecab libmecab-dev mecab-ipadic mecab-ipadic-utf8 mecab-utils mecab-jumandic mecab-jumandic-utf8
          sudo apt-get autoremove -y
          sudo apt-get clean
          echo "--- Finished purging MeCab packages ---"

          echo "--- Installing MeCab and dictionary (trying naist-jdic or jumandic-utf8) ---"
          sudo apt-get install -y mecab libmecab-dev mecab-utils
          if sudo apt-get install -y mecab-naist-jdic; then
            echo "mecab-naist-jdic installed."
            MECAB_DIC_PATH_SRC="/usr/share/mecab/dic/naist-jdic"
            MECAB_ENCODING_SRC="euc-jp"
          elif sudo apt-get install -y mecab-jumandic-utf8; then
            echo "mecab-jumandic-utf8 installed."
            MECAB_DIC_PATH_SRC="/usr/share/mecab/dic/juman"
            MECAB_ENCODING_SRC="utf-8"
          else
            echo "Error: Could not install a suitable MeCab dictionary (naist-jdic or jumandic-utf8)."
            exit 1
          fi
          echo "--- Finished installing MeCab and dictionary ---"
          echo "Using source dictionary from: $MECAB_DIC_PATH_SRC with encoding $MECAB_ENCODING_SRC"

          MECAB_DIC_PATH_COMPILED_UTF8="/usr/local/share/mecab-dic-compiled-utf8"
          sudo mkdir -p "$MECAB_DIC_PATH_COMPILED
