name: Fetch and Notify News

on:
  schedule:
    - cron: '0 * * * *'        # 毎時0分（UTC）
  workflow_dispatch:          # 手動実行トリガー

permissions:
  contents: write             # リポジトリへの書き込みを許可

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # 認証情報を明示的に渡す
          persist-credentials: true            # git push に GITHUB_TOKEN を使わせる

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install feedparser

      - name: Fetch CoinDesk RSS and save
        run: |
          mkdir -p data
          source .venv/bin/activate
          python news_fetcher.py > data/latest.txt

      - name: Commit fetched news
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add data/latest.txt
          git commit -m "chore: update latest CoinDesk news" || echo "No changes to commit"

      - name: Push changes
        if: ${{ steps.Commit_fetched_news.outcome == 'success' }}
        run: |
          git push origin main

      - name: Notify Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          payload=$(jq -R -s '{content: .}' data/latest.txt)
          curl -H "Content-Type: application/json" \
               -d "$payload" \
               "$DISCORD_WEBHOOK_URL"
