name: Fetch and Notify News

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install feedparser

      - name: Fetch CoinDesk RSS and save
        run: |
          mkdir -p data
          source .venv/bin/activate
          python news_fetcher.py > data/latest.txt

      - name: Commit fetched news
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add data/latest.txt
          git commit -m "chore: update latest CoinDesk news" || echo "No changes to commit"

      - name: Push changes
        run: git push origin main

      - name: Notify Discord (latest 5 articles)
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          # 最新5行だけ切り出し
          content="$(head -n 5 data/latest.txt)"
          # JSONペイロード作成
          payload=$(jq -Rn --arg c "$content" '{content: $c}')
          # Discordへ送信
          curl -H "Content-Type: application/json" \
               -d "$payload" \
               "$DISCORD_WEBHOOK_URL"
